title: newhigen
description: newhigen's blog
theme: just-the-docs

url: https://newhigen.github.io

aux_links:

color_scheme: custom

nav_external_links:
  - title: 읽은 책
    url: https://newhigen.github.io/books
    hide_icon: false
    opens_in_new_tab: true

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true
