title: newhigen
description: newhigen's blog
theme: just-the-docs

url: https://newhigen.github.io

aux_links:
  "About": /about.html
  "GitHub": https://github.com/newhigen
  "읽은 책": https://newhigen.github.io/books
aux_links_new_tab: false

color_scheme: custom

nav_external_links:

back_to_top: true
back_to_top_text: "Back to top"

enable_copy_code_button: true

ga_tracking: G-1LV633QRNR
ga_tracking_anonymize_ip: true

search_enabled: false

plugins:
  - jekyll-sitemap
